In [161]:
from gurobipy import GRB
import gurobipy as gb
import pandas as pd
import numpy as np

In [162]:
# Create the optimization model
model = gb.Model("Question 1")

In [163]:
nutrition_requirements_df = pd.read_csv(r"C:\Users\gabri\Downloads\nutrient_requirements.csv")
food_categories_df = pd.read_csv(r"C:\Users\gabri\Downloads\food_categories.csv")
food_preferences_df = pd.read_csv(r"C:\Users\gabri\Downloads\food_preferences.csv")
nutrition_content_df = pd.read_csv(r"C:\Users\gabri\Downloads\nutrient_content.csv")

In [164]:
nutrition_requirements_df

Nutrient  Min_Requirement  Max_Requirement
0    Nutrient_1      3831.321698      8474.081720
1    Nutrient_2      2251.071301      8403.640809
2    Nutrient_3      2975.778588      9619.196273
3    Nutrient_4      3284.851614      9534.776337
4    Nutrient_5      3139.208223      9622.440982
5    Nutrient_6      3778.988620      9514.680273
6    Nutrient_7      3368.066911      8191.724092
7    Nutrient_8      3650.066262      9765.756832
8    Nutrient_9      3324.251821      8755.235098
9   Nutrient_10      2688.486944      8439.329026
10  Nutrient_11      2545.167593      9135.133922
11  Nutrient_12      2699.922686      8691.729513
12  Nutrient_13      2816.356288      9419.739549
13  Nutrient_14      3653.614947      9389.237224
14  Nutrient_15      3421.872102      9700.214906
15  Nutrient_16      3653.684729      9987.117115
16  Nutrient_17      3850.272792      9599.127860
17  Nutrient_18      3629.594318      8283.097944
18  Nutrient_19      3924.555150      9525.285590
19  Nutrient_20      3899.722879      9133.799077
20  Nutrient_21      2641.923569      9126.362482
21  Nutrient_22      2784.614119      8674.491291
22  Nutrient_23      3150.411589      8321.465962
23  Nutrient_24      3381.092393      8346.103882
24  Nutrient_25      2929.411342      8115.199013
25  Nutrient_26      3575.538057      9610.699650
26  Nutrient_27      3264.013626      9487.896856
27  Nutrient_28      3191.740558      9713.457216
28  Nutrient_29      2290.790238      9408.286260
29  Nutrient_30      2342.628861      8335.572006
30  Nutrient_31      2626.574458      9471.918040
31  Nutrient_32      3924.950008      9115.703863
32  Nutrient_33      2152.420696      8217.345907
33  Nutrient_34      3920.502475      9810.244699
34  Nutrient_35      2954.214463      9804.634205
35  Nutrient_36      2871.922506      9255.728409
36  Nutrient_37      3693.759728      8839.282440
37  Nutrient_38      3662.952296      8475.848206
38  Nutrient_39      2267.968018      8195.201051
39  Nutrient_40      3623.488800      9611.998998
40  Nutrient_41      3021.406725      9933.506156
41  Nutrient_42      2646.254190      8028.081264
42  Nutrient_43      2216.758458      8958.722574
43  Nutrient_44      3184.455477      8212.071575
44  Nutrient_45      3560.663012      8837.078084
45  Nutrient_46      3771.349031      9161.225589
46  Nutrient_47      3943.238206      8858.201321
47  Nutrient_48      2246.377042      8034.446966
48  Nutrient_49      2793.568001      9975.689535
49  Nutrient_50      2097.352919      9851.608521
50  Nutrient_51      3271.487967      9544.746215
51  Nutrient_52      3775.339219      8801.361798
52  Nutrient_53      3374.526138      9378.980363
53  Nutrient_54      2777.418272      9419.536753
54  Nutrient_55      3519.847712      8680.509282
55  Nutrient_56      3993.225886      8079.373028
56  Nutrient_57      2002.244079      9244.629034
57  Nutrient_58      3656.111621      9896.167491
58  Nutrient_59      2652.543234      9495.574580
59  Nutrient_60      3494.132941      8455.974777

In [165]:
food_categories_df

Food_Item  Is_Vegetarian  Is_Vegan  Is_Kosher  Is_Halal  Cost_per_gram
0      Food_1              1         1          1         1       0.132322
1      Food_2              0         0          0         0       0.157278
2      Food_3              1         1          1         1       0.140415
3      Food_4              0         0          0         0       0.131732
4      Food_5              0         0          1         1       0.113548
..        ...            ...       ...        ...       ...            ...
115  Food_116              0         0          0         0       0.109476
116  Food_117              0         0          1         1       0.182165
117  Food_118              0         0          0         0       0.137191
118  Food_119              1         1          0         0       0.182260
119  Food_120              0         0          0         0       0.153880

[120 rows x 6 columns]

In [166]:
food_preferences_df

Veggie_grams  Vegan_grams  Kosher_grams  Halal_grams  All_grams
0       46160.0      11540.0       17310.0      92320.0     577000

In [167]:
nutrition_content_df

Unnamed: 0  Nutrient_1  Nutrient_2  Nutrient_3  Nutrient_4  Nutrient_5   
0       Food_1    0.007527    0.005512    0.009605    0.006796    0.004815  \
1       Food_2    0.002482    0.006593    0.006195    0.003141    0.009408   
2       Food_3    0.008775    0.002058    0.005656    0.002189    0.007452   
3       Food_4    0.009159    0.007966    0.003998    0.001730    0.004665   
4       Food_5    0.002684    0.009136    0.005894    0.005112    0.008938   
..         ...         ...         ...         ...         ...         ...   
115   Food_116    0.002451    0.008111    0.009838    0.001967    0.008573   
116   Food_117    0.009729    0.001609    0.002689    0.003863    0.009515   
117   Food_118    0.001119    0.004826    0.006940    0.008769    0.001294   
118   Food_119    0.001298    0.009726    0.008229    0.001675    0.008202   
119   Food_120    0.007274    0.005423    0.004822    0.003084    0.009887   

     Nutrient_6  Nutrient_7  Nutrient_8  Nutrient_9  ...  Nutrient_51   
0      0.006458    0.001173    0.003714    0.006942  ...     0.005689  \
1      0.006526    0.005821    0.006309    0.007571  ...     0.003285   
2      0.004565    0.006089    0.002650    0.002304  ...     0.004317   
3      0.003090    0.002192    0.001481    0.007530  ...     0.006810   
4      0.005127    0.007518    0.004591    0.009136  ...     0.001140   
..          ...         ...         ...         ...  ...          ...   
115    0.005408    0.001463    0.005692    0.005337  ...     0.007032   
116    0.003057    0.006086    0.002060    0.003436  ...     0.006986   
117    0.009477    0.008963    0.008863    0.006784  ...     0.001702   
118    0.006964    0.009152    0.005120    0.005530  ...     0.006204   
119    0.002113    0.002831    0.004397    0.002180  ...     0.006791   

     Nutrient_52  Nutrient_53  Nutrient_54  Nutrient_55  Nutrient_56   
0       0.001489     0.002800     0.001167     0.008143     0.003015  \
1       0.002920     0.005664     0.001231     0.002867     0.004822   
2       0.002232     0.008399     0.002709     0.005602     0.003019   
3       0.001318     0.004874     0.005590     0.005826     0.007133   
4       0.004859     0.001613     0.003267     0.002990     0.003279   
..           ...          ...          ...          ...          ...   
115     0.004821     0.007372     0.006519     0.004974     0.005941   
116     0.009281     0.006644     0.008465     0.007158     0.009525   
117     0.005247     0.006531     0.009452     0.009291     0.006467   
118     0.001681     0.003823     0.009844     0.006520     0.004778   
119     0.003754     0.008783     0.006342     0.004496     0.003900   

     Nutrient_57  Nutrient_58  Nutrient_59  Nutrient_60  
0       0.004108     0.009353     0.007340     0.001287  
1       0.004368     0.005172     0.003499     0.006281  
2       0.001881     0.008760     0.009756     0.009648  
3       0.003498     0.002160     0.004534     0.009608  
4       0.002179     0.001108     0.002039     0.006566  
..           ...          ...          ...          ...  
115     0.006383     0.008912     0.007092     0.007424  
116     0.004665     0.007955     0.005583     0.001445  
117     0.005524     0.006854     0.009325     0.009918  
118     0.009241     0.004252     0.007724     0.002316  
119     0.002023     0.006492     0.008043     0.004802  

[120 rows x 61 columns]

In [168]:
food_cost_per_gram = food_categories_df['Cost_per_gram'].values
food_cost_per_gram

array([0.13232203, 0.1572784 , 0.14041451, 0.13173248, 0.11354822,
       0.14688412, 0.11563808, 0.18376595, 0.19454941, 0.10751623,
       0.16875876, 0.12933424, 0.13520668, 0.1888395 , 0.06065541,
       0.06306939, 0.05303276, 0.17489298, 0.16672351, 0.18050182,
       0.19679275, 0.16987378, 0.1192219 , 0.16707938, 0.06774116,
       0.14598815, 0.07150299, 0.19170034, 0.12827725, 0.11219929,
       0.08968334, 0.16613505, 0.11842255, 0.13526509, 0.05281847,
       0.14264532, 0.14181436, 0.1425401 , 0.19156221, 0.15227304,
       0.10392619, 0.11555479, 0.15464468, 0.05903382, 0.15001501,
       0.15059568, 0.08155738, 0.06933894, 0.09731425, 0.10455662,
       0.13552952, 0.11579023, 0.19825608, 0.06530672, 0.08133151,
       0.07419643, 0.14796625, 0.08799374, 0.11994662, 0.08666384,
       0.07384544, 0.06655627, 0.14844944, 0.07072744, 0.07948735,
       0.10530878, 0.17314898, 0.06456519, 0.17569174, 0.06441476,
       0.19646892, 0.12029768, 0.19651416, 0.14072683, 0.16088

In [169]:
# x is the amount of food in grams
x = model.addVars(120, lb=0, vtype=GRB.CONTINUOUS, name="Food in Grams")

In [170]:
# The objective function
objective = gb.quicksum(food_cost_per_gram[i]*x[i] for i in range(120))
model.setObjective(objective, GRB.MINIMIZE)

In [171]:
nutrition_content_df = nutrition_content_df.drop(nutrition_content_df.columns[0], axis=1)
nutrition_content_df

Nutrient_1  Nutrient_2  Nutrient_3  Nutrient_4  Nutrient_5  Nutrient_6   
0      0.007527    0.005512    0.009605    0.006796    0.004815    0.006458  \
1      0.002482    0.006593    0.006195    0.003141    0.009408    0.006526   
2      0.008775    0.002058    0.005656    0.002189    0.007452    0.004565   
3      0.009159    0.007966    0.003998    0.001730    0.004665    0.003090   
4      0.002684    0.009136    0.005894    0.005112    0.008938    0.005127   
..          ...         ...         ...         ...         ...         ...   
115    0.002451    0.008111    0.009838    0.001967    0.008573    0.005408   
116    0.009729    0.001609    0.002689    0.003863    0.009515    0.003057   
117    0.001119    0.004826    0.006940    0.008769    0.001294    0.009477   
118    0.001298    0.009726    0.008229    0.001675    0.008202    0.006964   
119    0.007274    0.005423    0.004822    0.003084    0.009887    0.002113   

     Nutrient_7  Nutrient_8  Nutrient_9  Nutrient_10  ...  Nutrient_51   
0      0.001173    0.003714    0.006942     0.003611  ...     0.005689  \
1      0.005821    0.006309    0.007571     0.003808  ...     0.003285   
2      0.006089    0.002650    0.002304     0.005393  ...     0.004317   
3      0.002192    0.001481    0.007530     0.001103  ...     0.006810   
4      0.007518    0.004591    0.009136     0.007210  ...     0.001140   
..          ...         ...         ...          ...  ...          ...   
115    0.001463    0.005692    0.005337     0.009023  ...     0.007032   
116    0.006086    0.002060    0.003436     0.003485  ...     0.006986   
117    0.008963    0.008863    0.006784     0.005200  ...     0.001702   
118    0.009152    0.005120    0.005530     0.008536  ...     0.006204   
119    0.002831    0.004397    0.002180     0.009418  ...     0.006791   

     Nutrient_52  Nutrient_53  Nutrient_54  Nutrient_55  Nutrient_56   
0       0.001489     0.002800     0.001167     0.008143     0.003015  \
1       0.002920     0.005664     0.001231     0.002867     0.004822   
2       0.002232     0.008399     0.002709     0.005602     0.003019   
3       0.001318     0.004874     0.005590     0.005826     0.007133   
4       0.004859     0.001613     0.003267     0.002990     0.003279   
..           ...          ...          ...          ...          ...   
115     0.004821     0.007372     0.006519     0.004974     0.005941   
116     0.009281     0.006644     0.008465     0.007158     0.009525   
117     0.005247     0.006531     0.009452     0.009291     0.006467   
118     0.001681     0.003823     0.009844     0.006520     0.004778   
119     0.003754     0.008783     0.006342     0.004496     0.003900   

     Nutrient_57  Nutrient_58  Nutrient_59  Nutrient_60  
0       0.004108     0.009353     0.007340     0.001287  
1       0.004368     0.005172     0.003499     0.006281  
2       0.001881     0.008760     0.009756     0.009648  
3       0.003498     0.002160     0.004534     0.009608  
4       0.002179     0.001108     0.002039     0.006566  
..           ...          ...          ...          ...  
115     0.006383     0.008912     0.007092     0.007424  
116     0.004665     0.007955     0.005583     0.001445  
117     0.005524     0.006854     0.009325     0.009918  
118     0.009241     0.004252     0.007724     0.002316  
119     0.002023     0.006492     0.008043     0.004802  

[120 rows x 60 columns]

In [172]:
min_nutrition = nutrition_requirements_df['Min_Requirement'].values
min_nutrition

array([3831.32169799, 2251.07130055, 2975.77858839, 3284.85161415,
       3139.20822272, 3778.98862023, 3368.06691136, 3650.06626199,
       3324.25182144, 2688.48694433, 2545.16759297, 2699.92268582,
       2816.35628843, 3653.61494701, 3421.87210154, 3653.68472888,
       3850.27279224, 3629.5943176 , 3924.55514966, 3899.72287911,
       2641.92356851, 2784.61411856, 3150.41158887, 3381.09239261,
       2929.4113416 , 3575.53805705, 3264.0136257 , 3191.74055795,
       2290.79023798, 2342.62886146, 2626.57445812, 3924.95000811,
       2152.42069602, 3920.50247543, 2954.21446283, 2871.92250639,
       3693.75972781, 3662.95229602, 2267.96801766, 3623.48879979,
       3021.406725  , 2646.25418967, 2216.75845831, 3184.4554769 ,
       3560.66301159, 3771.34903126, 3943.23820561, 2246.37704222,
       2793.56800072, 2097.35291934, 3271.48796679, 3775.33921929,
       3374.52613776, 2777.41827197, 3519.84771198, 3993.22588644,
       2002.24407874, 3656.11162066, 2652.54323374, 3494.13294

In [173]:
max_nutrition = nutrition_requirements_df['Max_Requirement'].values
max_nutrition

array([8474.08172041, 8403.64080932, 9619.19627339, 9534.77633729,
       9622.44098174, 9514.68027325, 8191.72409178, 9765.75683172,
       8755.23509795, 8439.3290262 , 9135.1339224 , 8691.72951267,
       9419.73954871, 9389.23722396, 9700.21490647, 9987.11711506,
       9599.12786004, 8283.09794435, 9525.28558991, 9133.79907677,
       9126.36248191, 8674.49129125, 8321.46596167, 8346.10388236,
       8115.19901255, 9610.6996499 , 9487.89685597, 9713.45721552,
       9408.2862601 , 8335.57200612, 9471.91803961, 9115.70386307,
       8217.34590663, 9810.24469921, 9804.63420532, 9255.72840934,
       8839.28243959, 8475.84820642, 8195.2010514 , 9611.99899783,
       9933.50615572, 8028.08126425, 8958.72257397, 8212.0715752 ,
       8837.0780838 , 9161.22558911, 8858.20132053, 8034.44696616,
       9975.68953521, 9851.60852078, 9544.74621547, 8801.36179771,
       9378.98036285, 9419.53675292, 8680.5092824 , 8079.37302792,
       9244.62903419, 9896.16749055, 9495.57457973, 8455.97477

In [174]:
nutrient_totals = nutrition_content_df.sum(axis=0)
nutrient_totals

Nutrient_1     0.643452
Nutrient_2     0.667322
Nutrient_3     0.625245
Nutrient_4     0.696926
Nutrient_5     0.711545
Nutrient_6     0.650779
Nutrient_7     0.656501
Nutrient_8     0.670096
Nutrient_9     0.667193
Nutrient_10    0.644050
Nutrient_11    0.667856
Nutrient_12    0.592311
Nutrient_13    0.669681
Nutrient_14    0.584951
Nutrient_15    0.646069
Nutrient_16    0.665710
Nutrient_17    0.631176
Nutrient_18    0.640167
Nutrient_19    0.640895
Nutrient_20    0.648962
Nutrient_21    0.633524
Nutrient_22    0.681560
Nutrient_23    0.622871
Nutrient_24    0.687119
Nutrient_25    0.632561
Nutrient_26    0.674372
Nutrient_27    0.673781
Nutrient_28    0.658023
Nutrient_29    0.676444
Nutrient_30    0.681505
Nutrient_31    0.650513
Nutrient_32    0.640962
Nutrient_33    0.654234
Nutrient_34    0.656598
Nutrient_35    0.625163
Nutrient_36    0.639321
Nutrient_37    0.644562
Nutrient_38    0.663460
Nutrient_39    0.700490
Nutrient_40    0.660301
Nutrient_41    0.696462
Nutrient_42    0

In [175]:
for j in range(60):  # Loop over nutrient categories
    model.addConstr(gb.quicksum(nutrition_content_df.iloc[i,j] * x[i] for i in range(120)) >= min_nutrition[j])
    model.addConstr(gb.quicksum(nutrition_content_df.iloc[i,j] * x[i] for i in range(120)) <= max_nutrition[j])

In [176]:
food_categories_df

Food_Item  Is_Vegetarian  Is_Vegan  Is_Kosher  Is_Halal  Cost_per_gram
0      Food_1              1         1          1         1       0.132322
1      Food_2              0         0          0         0       0.157278
2      Food_3              1         1          1         1       0.140415
3      Food_4              0         0          0         0       0.131732
4      Food_5              0         0          1         1       0.113548
..        ...            ...       ...        ...       ...            ...
115  Food_116              0         0          0         0       0.109476
116  Food_117              0         0          1         1       0.182165
117  Food_118              0         0          0         0       0.137191
118  Food_119              1         1          0         0       0.182260
119  Food_120              0         0          0         0       0.153880

[120 rows x 6 columns]

In [177]:
food_preferences_df

Veggie_grams  Vegan_grams  Kosher_grams  Halal_grams  All_grams
0       46160.0      11540.0       17310.0      92320.0     577000

In [178]:
veg = food_categories_df['Is_Vegetarian'].values
veg

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [179]:
veg_grams = food_preferences_df['Veggie_grams'].values
veg_grams

array([46160.])

In [180]:
veg_variety  = model.addConstr(gb.quicksum(veg[i]*x[i] for i in range (120)) >= veg_grams, "Veggie Preferences")

In [181]:
vegan = food_categories_df['Is_Vegan'].values
vegan
vegan_grams = food_preferences_df['Vegan_grams'].values
vegan_grams
vegan_variety = model.addConstr(gb.quicksum(vegan[i]*x[i] for i in range (120)) >= vegan_grams, "Vegan Preferences")

In [182]:
kosher = food_categories_df['Is_Kosher'].values
kosher
kosher_grams = food_preferences_df['Kosher_grams'].values
kosher_grams
kosher_variety = model.addConstr(gb.quicksum(kosher[i]*x[i] for i in range (120)) >= kosher_grams, "Kosher Preferences")

In [183]:
halal = food_categories_df['Is_Halal'].values
halal
halal_grams = food_preferences_df['Halal_grams'].values
halal_grams
halal_variety = model.addConstr(gb.quicksum(halal[i]*x[i] for i in range (120)) >= halal_grams, "Halal Preferences")

In [184]:
all = food_preferences_df['All_grams'].values
all

array([577000], dtype=int64)

In [185]:
model.addConstr(gb.quicksum(veg[i]*x[i] for i in range (120)) + gb.quicksum(vegan[i]*x[i] for i in range (120)) + gb.quicksum(kosher[i]*x[i] for i in range (120)) + gb.quicksum(halal[i]*x[i] for i in range (120)) >= all, "Vegan Preferences")

<gurobi.Constr *Awaiting Model Update*>

In [186]:
for i in range(120):
    variety = model.addConstr(x[i] <= 0.03 * gb.quicksum(x[j] for j in range(120)))

In [187]:
model.optimize()

Gurobi Optimizer version 11.0.0 build v11.0.0rc2 (win64 - Windows 11+.0 (22631.2))

CPU model: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 245 rows, 120 columns and 29038 nonzeros
Model fingerprint: 0xbf96d785
Coefficient statistics:
  Matrix range     [1e-03, 4e+00]
  Objective range  [5e-02, 2e-01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+03, 6e+05]
Presolve removed 62 rows and 0 columns
Presolve time: 0.01s
Presolved: 183 rows, 180 columns, 21814 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    0.0000000e+00   9.438701e+04   0.000000e+00      0s
      88    5.4312000e+04   0.000000e+00   0.000000e+00      0s

Solved in 88 iterations and 0.02 seconds (0.02 work units)
Optimal objective  5.431199981e+04


In [188]:
# Print the decision variables
print(model.printAttr('X'))


    Variable            X 
-------------------------
Food in Grams[14]        22253 
Food in Grams[15]        22253 
Food in Grams[16]        22253 
Food in Grams[24]        22253 
Food in Grams[26]        22253 
Food in Grams[30]        22253 
Food in Grams[34]        22253 
Food in Grams[40]      5968.89 
Food in Grams[41]      10225.5 
Food in Grams[43]        22253 
Food in Grams[46]        22253 
Food in Grams[47]        22253 
Food in Grams[48]       3581.3 
Food in Grams[53]        22253 
Food in Grams[54]        22253 
Food in Grams[60]        22253 
Food in Grams[61]        22253 
Food in Grams[63]        22253 
Food in Grams[64]      844.396 
Food in Grams[67]        22253 
Food in Grams[69]        22253 
Food in Grams[75]        22253 
Food in Grams[76]      18117.1 
Food in Grams[77]        22253 
Food in Grams[79]      15711.7 
Food in Grams[80]        22253 
Food in Grams[82]        22253 
Food in Grams[85]        22253 
Food in Grams[87]        22253 
Food in Grams[90] 

In [189]:
# Value of the objective function
print("Cost of the Diet: ", round(model.objVal, 2))

Cost of the Diet:  54312.0


In [190]:
num_constraints = model.NumConstrs
print("Number of constraints (excluding non-negativity):", num_constraints)

Number of constraints (excluding non-negativity): 245


In [191]:
grams = model.getAttr('X', x)
grams

{0: 0.0,
 1: 0.0,
 2: 0.0,
 3: 0.0,
 4: 0.0,
 5: 0.0,
 6: 0.0,
 7: 0.0,
 8: 0.0,
 9: 0.0,
 10: 0.0,
 11: 0.0,
 12: 0.0,
 13: 0.0,
 14: 22252.96516867106,
 15: 22252.96516867106,
 16: 22252.965168671064,
 17: 0.0,
 18: 0.0,
 19: 0.0,
 20: 0.0,
 21: 0.0,
 22: 0.0,
 23: 0.0,
 24: 22252.965168671064,
 25: 0.0,
 26: 22252.965168671064,
 27: 0.0,
 28: 0.0,
 29: 0.0,
 30: 22252.965168671053,
 31: 0.0,
 32: 0.0,
 33: 0.0,
 34: 22252.965168671064,
 35: 0.0,
 36: 0.0,
 37: 0.0,
 38: 0.0,
 39: 0.0,
 40: 5968.893167276643,
 41: 10225.481887700313,
 42: 0.0,
 43: 22252.965168671064,
 44: 0.0,
 45: 0.0,
 46: 22252.965168671075,
 47: 22252.96516867106,
 48: 3581.297321619381,
 49: 0.0,
 50: 0.0,
 51: 0.0,
 52: 0.0,
 53: 22252.96516867106,
 54: 22252.96516867106,
 55: 0.0,
 56: 0.0,
 57: 0.0,
 58: 0.0,
 59: 0.0,
 60: 22252.96516867106,
 61: 22252.965168671064,
 62: 0.0,
 63: 22252.965168671068,
 64: 844.3960579636497,
 65: 0.0,
 66: 0.0,
 67: 22252.96516867107,
 68: 0.0,
 69: 22252.965168671068,
 70: 

In [192]:
veg_amount = gb.quicksum(veg[i] * grams[i] for i in range (120))
print(veg_amount)

halal_amount = gb.quicksum(halal[i] * grams[i] for i in range (120))
print(halal_amount)

kosher_amount = gb.quicksum(kosher[i] * grams[i] for i in range (120))
print(kosher_amount)

332113.6271468517
268947.8566834641
268947.8566834641


In [193]:
print("")
print(f"Sensitivity Information for Land Capacity Constraint {variety.pi:.2f}:")
print("(LHS, RHS, Slack): ", (model.getRow(variety).getValue(), variety.RHS, variety.slack))
print("Shadow Price: ", variety.pi)
print("Range of Feasibility: ", (variety.SARHSUp, variety.SARHSLow))


Sensitivity Information for Land Capacity Constraint 0.00:
(LHS, RHS, Slack):  (-22252.96516867105, 0.0, 22252.96516867105)
Shadow Price:  0.0
Range of Feasibility:  (inf, -22252.96516867105)


In [194]:
print("")
print(f"Sensitivity Information for Land Capacity Constraint {veg_variety.pi:.2f}:")
print("(LHS, RHS, Slack): ", (model.getRow(veg_variety).getValue(), veg_variety.RHS, veg_variety.slack))
print("Shadow Price: ", veg_variety.pi)
print("Range of Feasibility: ", (veg_variety.SARHSUp, veg_variety.SARHSLow))


Sensitivity Information for Land Capacity Constraint 0.00:
(LHS, RHS, Slack):  (332113.6271468517, 46160.0, -285953.62714685174)
Shadow Price:  0.0
Range of Feasibility:  (332113.62714685174, -inf)


In [195]:
print("")
print(f"Sensitivity Information for Land Capacity Constraint {vegan_variety.pi:.2f}:")
print("(LHS, RHS, Slack): ", (model.getRow(vegan_variety).getValue(), vegan_variety.RHS, vegan_variety.slack))
print("Shadow Price: ", vegan_variety.pi)
print("Range of Feasibility: ", (vegan_variety.SARHSUp, vegan_variety.SARHSLow))


Sensitivity Information for Land Capacity Constraint 0.00:
(LHS, RHS, Slack):  (332113.6271468517, 11540.0, -320573.62714685174)
Shadow Price:  0.0
Range of Feasibility:  (332113.62714685174, -inf)


In [196]:
print("")
print(f"Sensitivity Information for Land Capacity Constraint {kosher_variety.pi:.2f}:")
print("(LHS, RHS, Slack): ", (model.getRow(kosher_variety).getValue(), kosher_variety.RHS, kosher_variety.slack))
print("Shadow Price: ", kosher_variety.pi)
print("Range of Feasibility: ", (kosher_variety.SARHSUp, kosher_variety.SARHSLow))


Sensitivity Information for Land Capacity Constraint 0.00:
(LHS, RHS, Slack):  (268947.8566834641, 17310.0, -251637.85668346405)
Shadow Price:  0.0
Range of Feasibility:  (268947.856683464, -inf)


In [197]:
print("")
print(f"Sensitivity Information for Land Capacity Constraint {halal_variety.pi:.2f}:")
print("(LHS, RHS, Slack): ", (model.getRow(halal_variety).getValue(), halal_variety.RHS, halal_variety.slack))
print("Shadow Price: ", halal_variety.pi)
print("Range of Feasibility: ", (halal_variety.SARHSUp, halal_variety.SARHSLow))


Sensitivity Information for Land Capacity Constraint 0.00:
(LHS, RHS, Slack):  (268947.8566834641, 92320.0, -176627.85668346405)
Shadow Price:  0.0
Range of Feasibility:  (268947.856683464, -inf)
